const fs = require('fs');
const path = require('path');

const srcDir = 'c:\\\\Users\\\\Administrador\\\\Desktop\\\\Dashboard Syscom\\\\frontend\\\\src';

function walkDir(dir, callback) {
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
    });
}

// 1. Process index.css
const cssPath = path.join(srcDir, 'index.css');
let css = fs.readFileSync(cssPath, 'utf8');

// Remove border from .card, .card-flat, .card-gradient, .glass, .input, .btn-secondary, .divider
css = css.replace(/border:\s*1px\s*solid\s*var\(--color-border-default\);/g, '');
css = css.replace(/border:\s*1px\s*solid\s*rgba\(255,\s*255,\s*255,\s*0\.2\);/g, '');
css = css.replace(/border:\s*1px\s*solid\s*var\(--color-slate-300\);/g, '');

css = css.replace(/background-color:\s*var\(--color-surface-primary\);\n\s*border-radius:\s*var\(--radius-xl\);\n\s*box-shadow:\s*var\(--shadow-card\);/g, 'background: linear-gradient(to bottom, #ffffff, #f8fafc);\n    border-radius: var(--radius-xl);\n    box-shadow: var(--shadow-card);');

css = css.replace(/\.input\s*{([^}]*)}/g, (match, inner) => {
    return `.input {${inner.replace('background-color: var(--color-surface-primary);', 'background-color: var(--color-slate-100);\n    box-shadow: inset 0 2px 4px 0 rgba(0, 0, 0, 0.02);')}}`;
});

css = css.replace(/\.input:focus\s*{([^}]*)}/g, (match, inner) => {
    return `.input:focus {\n    background-color: var(--color-surface-primary);\n    box-shadow: 0 0 0 4px var(--color-primary-100), 0 4px 12px rgba(0,0,0,0.05);\n    outline: none;\n  }`;
});

css = css.replace(/\.btn-secondary\s*{([^}]*)}/g, (match, inner) => {
    return `.btn-secondary {\n    background-color: var(--color-slate-100);\n    color: var(--color-slate-700);\n    box-shadow: var(--shadow-sm);\n  }`;
});

css = css.replace(/\.divider\s*{([^}]*)}/g, (match, inner) => {
    return `.divider {\n    background-color: var(--color-slate-100);\n    height: 1px;\n    margin: 1rem 0;\n  }`;
});

fs.writeFileSync(cssPath, css);


// 2. Process TSX files
walkDir(srcDir, function(filePath) {
    if (!filePath.endsWith('.tsx') && !filePath.endsWith('.ts')) return;
    
    let content = fs.readFileSync(filePath, 'utf8');
    let original = content;
    
    const borders = [
        /\bborder(-[tbrlxy])?\b/g,
        /\bborder-(slate|gray|white|transparent|primary|danger|success|warning|info|indigo|blue|red|green|yellow)(-\d+)?(\/\d+)?\b/g,
        /\bborder-(solid|dashed|dotted|double|hidden|none)\b/g,
        /\bborder-white\/5\b/g,
        /\bborder-slate-200\/60\b/g,
        /\bborder-slate-100\/50\b/g,
        /\bborder-t-slate-200\b/g,
        /\bborder-b-slate-200\b/g,
        /\bborder-b-slate-100\b/g,
    ];
    
    borders.forEach(regex => {
        content = content.replace(regex, '');
    });
    
    // Replace divides with nothing, or space-y. If it's x, maybe space-x-2.
    // Let's just remove them and if needed we can add gaps. Often flex handles it.
    content = content.replace(/\bdivide-[xy]\b/g, '');
    content = content.replace(/\bdivide-(slate|gray|white|transparent|primary|danger|success|warning|info)(-\d+)?(\/\d+)?\b/g, '');
    
    // Specific fixes
    if(filePath.includes('Sidebar.tsx')) {
       content = content.replace('bg-slate-900', 'bg-gradient-to-b from-slate-900 to-slate-950 shadow-[4px_0_24px_rgba(0,0,0,0.1)]');
    }
    if(filePath.includes('Header.tsx')) {
       content = content.replace('bg-white', 'bg-white/80 backdrop-blur-md shadow-sm');
    }
    if(filePath.includes('MobileNav.tsx')) {
       content = content.replace('bg-white', 'bg-white shadow-[0_-4px_12px_rgba(0,0,0,0.05)]');
    }
    if(filePath.includes('DataTable.tsx')) {
        // Find tr map and add alternates.
        content = content.replace(/<tr([^>]*)>/g, (match) => {
            if (match.includes('className=')) return match;
            return `<tr${match.slice(3,-1)} className="even:bg-slate-50 hover:bg-slate-100/50 transition-colors">`;
        });
        content = content.replace(/<thead([^>]*)>/g, (match) => {
            if (match.includes('className=')) return match;
            return `<thead${match.slice(6,-1)} className="bg-slate-100/50">`;
        });
    }

    if (original !== content) {
        // Let's clean up any double spaces generated by removing classes
        content = content.replace(/ className="[\s]+/g, ' className="');
        content = content.replace(/[\s]+" /g, '" ');
        fs.writeFileSync(filePath, content);
        console.log('Modified:', filePath);
    }
});
